title: Awesome Indonesian LLM Dataset
description: A curated collection of high-quality Indonesian datasets for LLMs and multimodal AI systems
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter

relative_links:
  enabled: true
  collections: true

markdown: kramdown
highlighter: rouge

include:
  - README.md
  - data/

exclude:
  - node_modules/
  - .gitignore
